export declare enum Permission {
    RELEASE_CREATE = "RELEASE_CREATE",
    RELEASE_READ = "RELEASE_READ",
    RELEASE_UPDATE = "RELEASE_UPDATE",
    RELEASE_DELETE = "RELEASE_DELETE",
    RELEASE_APPROVE = "RELEASE_APPROVE",
    RELEASE_DEPLOY = "RELEASE_DEPLOY",
    RELEASE_ROLLBACK = "RELEASE_ROLLBACK",
    RISK_TRIGGER = "RISK_TRIGGER",
    RISK_READ = "RISK_READ",
    RISK_OVERRIDE = "RISK_OVERRIDE",
    POLICY_CREATE = "POLICY_CREATE",
    POLICY_READ = "POLICY_READ",
    POLICY_UPDATE = "POLICY_UPDATE",
    POLICY_DELETE = "POLICY_DELETE",
    AUDIT_READ = "AUDIT_READ",
    AUDIT_EXPORT = "AUDIT_EXPORT",
    USER_MANAGE = "USER_MANAGE",
    ROLE_ASSIGN = "ROLE_ASSIGN",
    SYSTEM_CONFIG = "SYSTEM_CONFIG"
}
//# sourceMappingURL=permissions.enum.d.ts.map