export enum Permission {
  // Release permissions
  RELEASE_CREATE = 'RELEASE_CREATE',
  RELEASE_READ = 'RELEASE_READ',
  RELEASE_UPDATE = 'RELEASE_UPDATE',
  RELEASE_DELETE = 'RELEASE_DELETE',
  RELEASE_APPROVE = 'RELEASE_APPROVE',
  RELEASE_DEPLOY = 'RELEASE_DEPLOY',
  RELEASE_ROLLBACK = 'RELEASE_ROLLBACK',

  // Risk permissions
  RISK_TRIGGER = 'RISK_TRIGGER',
  RISK_READ = 'RISK_READ',
  RISK_OVERRIDE = 'RISK_OVERRIDE',

  // Policy permissions
  POLICY_CREATE = 'POLICY_CREATE',
  POLICY_READ = 'POLICY_READ',
  POLICY_UPDATE = 'POLICY_UPDATE',
  POLICY_DELETE = 'POLICY_DELETE',

  // Audit permissions
  AUDIT_READ = 'AUDIT_READ',
  AUDIT_EXPORT = 'AUDIT_EXPORT',

  // Admin permissions
  USER_MANAGE = 'USER_MANAGE',
  ROLE_ASSIGN = 'ROLE_ASSIGN',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',
}
