export declare enum ErrorCode {
    VALIDATION_ERROR = "VALIDATION_ERROR",
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    CONFLICT = "CONFLICT",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    ANALYSIS_TIMEOUT = "ANALYSIS_TIMEOUT",
    RELEASE_EMPTY_CHANGES = "RELEASE_EMPTY_CHANGES",
    POLICY_VIOLATION = "POLICY_VIOLATION",
    RISK_THRESHOLD_EXCEEDED = "RISK_THRESHOLD_EXCEEDED"
}
//# sourceMappingURL=error-codes.enum.d.ts.map